// @generated by scripts/generate_legacy_ui.ps1; do not edit by hand.
static TRACKS_1: &[LegacyTrack] = &[
    LegacyTrack { name: "出力速度", min: 0.0, max: 10000.0, default: 100.0, step: 0.01 },
    LegacyTrack { name: "出力頻度", min: 0.01, max: 50000.0, default: 100.0, step: 0.01 },
    LegacyTrack { name: "出力方向", min: -360.0, max: 360.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "拡散角度", min: 0.0, max: 180.0, default: 60.0, step: 1.0 },
];
static DIALOGS_1: &[LegacyDialog] = &[
    LegacyDialog { name: "同時発生数", key: "sync", default: "0" },
    LegacyDialog { name: "各xy重力", key: "grav", default: "{0,0}" },
    LegacyDialog { name: "加速度", key: "ac", default: "0" },
    LegacyDialog { name: "各xyz回転初期値", key: "rotxyz", default: "\"{0,0,r}\"" },
    LegacyDialog { name: "各xyz回転速度", key: "degvxyz", default: "{0,0,60}" },
    LegacyDialog { name: "逆回転有/chk", key: "revrot", default: "0" },
    LegacyDialog { name: "生存時間(秒", key: "ju", default: "3" },
    LegacyDialog { name: "透過率｛始、終｝", key: "palpha", default: "{100,50}" },
    LegacyDialog { name: "拡大率｛始、終｝", key: "pzoom", default: "{100,100}" },
    LegacyDialog { name: "開始時間", key: "tsub", default: "0" },
    LegacyDialog { name: "カメラを見る/chk", key: "cam", default: "0" },
    LegacyDialog { name: "平面描写/chk", key: "heymen", default: "0" },
    LegacyDialog { name: "平面領域", key: "plate", default: "{1280,720}" },
    LegacyDialog { name: "描写精度", key: "seiti", default: "2" },
    LegacyDialog { name: "風、ｸﾞﾘｯﾄﾞｽﾙｰ0~2", key: "throughf", default: "0" },
    LegacyDialog { name: "ｼｰﾄﾞ", key: "ran", default: "0" },
];

pub(super) static SCHEMA_1: LegacyEffectSchema = LegacyEffectSchema {
    name: "パーティクル本体", tracks: TRACKS_1, check: Some(LegacyCheck { name: "終了時に消える", default: false }), dialogs: DIALOGS_1, file_input: false,
};

static TRACKS_2: &[LegacyTrack] = &[
    LegacyTrack { name: "パス番号", min: 1.0, max: 10.0, default: 1.0, step: 1.0 },
];
static DIALOGS_2: &[LegacyDialog] = &[
];

pub(super) static SCHEMA_2: LegacyEffectSchema = LegacyEffectSchema {
    name: "パス", tracks: TRACKS_2, check: Some(LegacyCheck { name: "単体", default: false }), dialogs: DIALOGS_2, file_input: true,
};

static TRACKS_3: &[LegacyTrack] = &[
    LegacyTrack { name: "前⇔後", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "表裏(裏2", min: 0.0, max: 2.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "表裏合成", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "回転表現", min: 0.0, max: 6.0, default: 0.0, step: 1.0 },
];
static DIALOGS_3: &[LegacyDialog] = &[
    LegacyDialog { name: "頻度逆転/chk", key: "ref", default: "0" },
    LegacyDialog { name: "逆再生/chk", key: "rep", default: "0" },
    LegacyDialog { name: "進行方向を向く/chk", key: "prog", default: "0" },
    LegacyDialog { name: "ゲームで遊ぶ/chk", key: "game", default: "0" },
];

pub(super) static SCHEMA_3: LegacyEffectSchema = LegacyEffectSchema {
    name: "前後表裏その他切替", tracks: TRACKS_3, check: Some(LegacyCheck { name: "書出時間短縮(未だ使えない)", default: false }), dialogs: DIALOGS_3, file_input: false,
};

static TRACKS_4: &[LegacyTrack] = &[
    LegacyTrack { name: "z出力方向", min: -360.0, max: 360.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "z拡散角度", min: 0.0, max: 180.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "z重力", min: -10000.0, max: 10000.0, default: 0.0, step: 1.0 },
];
static DIALOGS_4: &[LegacyDialog] = &[
    LegacyDialog { name: "格子間隔x(r)", key: "gridx", default: "0" },
    LegacyDialog { name: "格子間隔y(theta)", key: "gridy", default: "0" },
    LegacyDialog { name: "格子間隔z(phy)", key: "gridz", default: "0" },
    LegacyDialog { name: "極座標切替/chk", key: "polar", default: "0" },
    LegacyDialog { name: "ｸﾞﾘｯﾄﾞ情報取得/chk", key: "griinf", default: "0" },
    LegacyDialog { name: "情報反転/chk", key: "gridrev", default: "0" },
    LegacyDialog { name: "二方向化/chk", key: "dua", default: "0" },
    LegacyDialog { name: "xy出力方向", key: "duaxy", default: "-180" },
    LegacyDialog { name: "xy拡散角度", key: "duaexy", default: "60" },
    LegacyDialog { name: "z出力方向", key: "duaz", default: "0" },
    LegacyDialog { name: "z拡散角度", key: "duaez", default: "0" },
];

pub(super) static SCHEMA_4: LegacyEffectSchema = LegacyEffectSchema {
    name: "方向と格子", tracks: TRACKS_4, check: None, dialogs: DIALOGS_4, file_input: false,
};

static TRACKS_5: &[LegacyTrack] = &[
    LegacyTrack { name: "数", min: 1.0, max: 16.0, default: 16.0, step: 1.0 },
    LegacyTrack { name: "出力ﾀｲﾌﾟ", min: 1.0, max: 8.0, default: 3.0, step: 1.0 },
    LegacyTrack { name: "値", min: 0.0, max: 100.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "ｵﾌﾟｼｮﾝ", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
];
static DIALOGS_5: &[LegacyDialog] = &[
    LegacyDialog { name: "ｵﾌﾟ2/chk", key: "o2", default: "0" },
    LegacyDialog { name: "line", key: "line", default: "{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}" },
];

pub(super) static SCHEMA_5: LegacyEffectSchema = LegacyEffectSchema {
    name: "出力", tracks: TRACKS_5, check: Some(LegacyCheck { name: "ライン合成", default: false }), dialogs: DIALOGS_5, file_input: false,
};

static TRACKS_6: &[LegacyTrack] = &[
    LegacyTrack { name: "揺れ速度", min: 0.0, max: 2000.0, default: 60.0, step: 1.0 },
    LegacyTrack { name: "x揺れ回転", min: 0.0, max: 1080.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "y揺れ回転", min: 0.0, max: 1080.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "z揺れ回転", min: 0.0, max: 1080.0, default: 0.0, step: 1.0 },
];
static DIALOGS_6: &[LegacyDialog] = &[
    LegacyDialog { name: "個別揺れ速度", key: "kv", default: "0" },
    LegacyDialog { name: "個別x揺れ回転", key: "yx", default: "0" },
    LegacyDialog { name: "個別y揺れ回転", key: "yy", default: "0" },
    LegacyDialog { name: "個別z揺れ回転", key: "yz", default: "0" },
    LegacyDialog { name: "揺れ同期/chk", key: "syncr", default: "0" },
    LegacyDialog { name: "x放射時角度増減", key: "upx", default: "0" },
    LegacyDialog { name: "y放射時角度増減", key: "upy", default: "0" },
    LegacyDialog { name: "z放射時角度増減", key: "upz", default: "0" },
    LegacyDialog { name: "各xyz回転加速度", key: "rxyzac", default: "{0,0,0}" },
    LegacyDialog { name: "加速度反転なし/chk", key: "no_ac", default: "1" },
    LegacyDialog { name: "x加速上限", key: "xlimit", default: "nil" },
    LegacyDialog { name: "y加速上限", key: "ylimit", default: "nil" },
    LegacyDialog { name: "z加速上限", key: "zlimit", default: "nil" },
    LegacyDialog { name: "各加速ﾀｲﾐﾝｸﾞms", key: "xyztim", default: "{0,0,0}" },
    LegacyDialog { name: "相対時間/chk", key: "abrot", default: "1" },
    LegacyDialog { name: "個別加速とﾀｲﾐﾝｸﾞ", key: "xyzb", default: "{0,0,0,0}" },
];

pub(super) static SCHEMA_6: LegacyEffectSchema = LegacyEffectSchema {
    name: "回転", tracks: TRACKS_6, check: Some(LegacyCheck { name: "出力角度位置ﾗﾝﾀﾞﾑ", default: true }), dialogs: DIALOGS_6, file_input: false,
};

static TRACKS_7: &[LegacyTrack] = &[
    LegacyTrack { name: "x座標", min: -8000.0, max: 8000.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "y座標", min: -8000.0, max: 8000.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "z座標", min: -8000.0, max: 8000.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "ｱﾝｶｰ数", min: -5.0, max: 5.0, default: 0.0, step: 1.0 },
];
static DIALOGS_7: &[LegacyDialog] = &[
    LegacyDialog { name: "ｱﾝｶｰ連結/chk", key: "anc", default: "0" },
    LegacyDialog { name: "各集結点座標", key: "pos", default: "{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}" },
    LegacyDialog { name: "集結開始時間ms", key: "contime", default: "0" },
    LegacyDialog { name: "↑相対時間/chk", key: "conab", default: "1" },
    LegacyDialog { name: "xy方向角度", key: "conxy", default: "0" },
    LegacyDialog { name: "xy拡散度", key: "econxy", default: "0" },
    LegacyDialog { name: "z方向角度", key: "conz", default: "0" },
    LegacyDialog { name: "z拡散度", key: "econz", default: "0" },
    LegacyDialog { name: "ｵﾌﾟｼｮﾝ0~2", key: "copti", default: "0" },
    LegacyDialog { name: "ｵﾌﾟ0~1集結後消滅/chk", key: "metsu", default: "0" },
    LegacyDialog { name: "消滅半径", key: "metsus", default: "100" },
    LegacyDialog { name: "滅せず停止/chk", key: "mstop", default: "0" },
    LegacyDialog { name: "ｵﾌﾟ2各集結時間", key: "contime2", default: "{}" },
    LegacyDialog { name: "集結時間個別", key: "ctimeb", default: "0" },
];

pub(super) static SCHEMA_7: LegacyEffectSchema = LegacyEffectSchema {
    name: "集結点", tracks: TRACKS_7, check: Some(LegacyCheck { name: "座標表示", default: true }), dialogs: DIALOGS_7, file_input: false,
};

static TRACKS_8: &[LegacyTrack] = &[
    LegacyTrack { name: "始拡大率", min: 0.0, max: 1000.0, default: 100.0, step: 1.0 },
    LegacyTrack { name: "終拡大率", min: 0.0, max: 1000.0, default: 100.0, step: 1.0 },
    LegacyTrack { name: "始透過率", min: 0.0, max: 1000.0, default: 100.0, step: 1.0 },
    LegacyTrack { name: "終透過率", min: 0.0, max: 1000.0, default: 100.0, step: 1.0 },
];
static DIALOGS_8: &[LegacyDialog] = &[
    LegacyDialog { name: "中点時間(拡)ms", key: "czoom", default: "{}" },
    LegacyDialog { name: "中間値(拡)", key: "nzoom", default: "{}" },
    LegacyDialog { name: "移動ﾀｲﾌﾟ(拡)0~", key: "tzoom", default: "{1}" },
    LegacyDialog { name: "個別時、値、ﾀ(拡)", key: "kzoom", default: "{0,0,0}" },
    LegacyDialog { name: "中点時間(透)ms", key: "calpha", default: "{}" },
    LegacyDialog { name: "中間値(透)", key: "nalpha", default: "{}" },
    LegacyDialog { name: "移動ﾀｲﾌﾟ(透)0~", key: "talpha", default: "{1}" },
    LegacyDialog { name: "個別時、値、ﾀ(透)", key: "kalpha", default: "{0,0,0}" },
    LegacyDialog { name: "反射中間点(拡)", key: "trzb", default: "nil" },
    LegacyDialog { name: "反射中間点(透)", key: "trab", default: "nil" },
    LegacyDialog { name: "分散中間点(拡)", key: "trzk", default: "nil" },
    LegacyDialog { name: "分散中間点(透)", key: "trak", default: "nil" },
    LegacyDialog { name: "ﾙｰﾌﾟ中間点(拡)", key: "cycz", default: "nil" },
    LegacyDialog { name: "ﾙｰﾌﾟ中間点(透)", key: "cyca", default: "nil" },
    LegacyDialog { name: "同時発生数同期/chk", key: "zalink", default: "0" },
];

pub(super) static SCHEMA_8: LegacyEffectSchema = LegacyEffectSchema {
    name: "拡大率と透過率", tracks: TRACKS_8, check: Some(LegacyCheck { name: "相対時間", default: true }), dialogs: DIALOGS_8, file_input: false,
};

static TRACKS_9: &[LegacyTrack] = &[
    LegacyTrack { name: "本体適用", min: 0.0, max: 1.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "軌跡適用", min: 0.0, max: 1.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "変化時間1", min: 0.0, max: 20000.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "変化時間2", min: 0.0, max: 20000.0, default: 0.0, step: 1.0 },
];
static DIALOGS_9: &[LegacyDialog] = &[
    LegacyDialog { name: "ﾌｨﾙﾀｰ名", key: "nae", default: "\"単色化\"" },
    LegacyDialog { name: "変化ﾊﾟﾗ名1", key: "paran1", default: "\"color\"" },
    LegacyDialog { name: "変化値1", key: "para1", default: "{0xff,0xff0000}" },
    LegacyDialog { name: "個別(四種)", key: "kpara1", default: "{10,0,0,0}" },
    LegacyDialog { name: "変化ﾊﾟﾗ名2", key: "paran2", default: "\"\"" },
    LegacyDialog { name: "変化値2", key: "para2", default: "{0,0}" },
    LegacyDialog { name: "特殊変化ﾊﾟﾗ名", key: "rann", default: "\"\"" },
    LegacyDialog { name: "特殊変化値", key: "rane", default: "\"{0,0}\"" },
    LegacyDialog { name: "固定ﾊﾟﾗ名1", key: "othern1", default: "\"輝度を保持する\"" },
    LegacyDialog { name: "固定ﾊﾟﾗ値1", key: "other1", default: "0" },
    LegacyDialog { name: "固定ﾊﾟﾗ名2", key: "othern2", default: "\"\"" },
    LegacyDialog { name: "固定ﾊﾟﾗ値2", key: "other2", default: "0" },
    LegacyDialog { name: "固定ﾊﾟﾗ名3", key: "othern3", default: "\"\"" },
    LegacyDialog { name: "固定ﾊﾟﾗ値3", key: "other3", default: "0" },
    LegacyDialog { name: "固定ﾊﾟﾗ名4", key: "othern4", default: "\"\"" },
    LegacyDialog { name: "固定ﾊﾟﾗ値4", key: "other4", default: "0" },
];

pub(super) static SCHEMA_9: LegacyEffectSchema = LegacyEffectSchema {
    name: "フィルター", tracks: TRACKS_9, check: Some(LegacyCheck { name: "相対時間", default: true }), dialogs: DIALOGS_9, file_input: false,
};

static TRACKS_10: &[LegacyTrack] = &[
    LegacyTrack { name: "本体適用", min: 0.0, max: 1.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "軌跡適用", min: 0.0, max: 1.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "相対時間", min: 0.0, max: 1.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "順番", min: 1.0, max: 11.0, default: 1.0, step: 1.0 },
];
static DIALOGS_10: &[LegacyDialog] = &[
    LegacyDialog { name: "強さ", key: "stro", default: "100" },
    LegacyDialog { name: "開始時間ms", key: "stime", default: "0" },
    LegacyDialog { name: "変化間隔ms", key: "ttime", default: "1000" },
    LegacyDialog { name: "持続間隔ms", key: "sttime", default: "1000" },
    LegacyDialog { name: "終了時間ms", key: "latime", default: "nil" },
    LegacyDialog { name: "パターン0~2", key: "pcol", default: "1" },
    LegacyDialog { name: "ﾗﾝﾀﾞﾑｶﾗｰ0~6", key: "rcol", default: "0" },
    LegacyDialog { name: "ｶﾗｰ0~4変化色", key: "tcol", default: "{0xff0000,0x00ff00,0x0000ff}" },
    LegacyDialog { name: "ｶﾗｰ4白み%黒み%", key: "sccol", default: "{50,50}" },
    LegacyDialog { name: "明るさ", key: "looks", default: "100" },
    LegacyDialog { name: "間隔で乱数変更", key: "tcha", default: "0" },
    LegacyDialog { name: "反射で乱数変更/chk", key: "bcha", default: "0" },
    LegacyDialog { name: "始めの色指定", key: "stcol", default: "\"\"" },
    LegacyDialog { name: "終りの色指定", key: "lacol", default: "\"\"" },
    LegacyDialog { name: "ｼｰﾄﾞ", key: "fseed", default: "0" },
    LegacyDialog { name: "16進数ｻﾝﾌﾟﾙ色/col", key: "scol", default: "0xffffff" },
];

pub(super) static SCHEMA_10: LegacyEffectSchema = LegacyEffectSchema {
    name: "フィルター(単色化専用)", tracks: TRACKS_10, check: Some(LegacyCheck { name: "輝度を保持する", default: true }), dialogs: DIALOGS_10, file_input: false,
};

static TRACKS_11: &[LegacyTrack] = &[
];
static DIALOGS_11: &[LegacyDialog] = &[
    LegacyDialog { name: "速度", key: "bv", default: "0" },
    LegacyDialog { name: "加速度", key: "bac", default: "0" },
    LegacyDialog { name: "各回転速度", key: "bro", default: "{0,0,0}" },
    LegacyDialog { name: "透過率{始、終}", key: "bal", default: "{0,0}" },
    LegacyDialog { name: "拡大率{始、終}", key: "bzo", default: "{0,0}" },
    LegacyDialog { name: "各重力", key: "bgv", default: "{0,0,0}" },
    LegacyDialog { name: "頻度", key: "bfr", default: "0" },
    LegacyDialog { name: "生存時間", key: "bju", default: "0" },
    LegacyDialog { name: "風力", key: "biwn", default: "0" },
    LegacyDialog { name: "ﾌｧﾝﾈﾙ数、円環数", key: "bfa", default: "{0,0}" },
    LegacyDialog { name: "ﾌｨﾙﾀ単色化", key: "bfc", default: "{0,0,0,0}" },
];

pub(super) static SCHEMA_11: LegacyEffectSchema = LegacyEffectSchema {
    name: "個別微調整", tracks: TRACKS_11, check: None, dialogs: DIALOGS_11, file_input: false,
};

static TRACKS_12: &[LegacyTrack] = &[
    LegacyTrack { name: "1速度", min: -10000.0, max: 10000.0, default: 100.0, step: 0.01 },
    LegacyTrack { name: "周期ms", min: 1.0, max: 90000.0, default: 500.0, step: 1.0 },
    LegacyTrack { name: "2加速度", min: -10000.0, max: 10000.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "周期ms", min: 1.0, max: 90000.0, default: 500.0, step: 1.0 },
];
static DIALOGS_12: &[LegacyDialog] = &[
    LegacyDialog { name: "3、4出力方向", key: "lod", default: "{0,0}" },
    LegacyDialog { name: "各周期ms", key: "dgs", default: "{500,500}" },
    LegacyDialog { name: "5、6拡散角度", key: "loe", default: "{0,0}" },
    LegacyDialog { name: "各周期ms [2]", key: "exs", default: "{500,500}" },
    LegacyDialog { name: "7、8、9回転速度", key: "rov", default: "{0,0,0}" },
    LegacyDialog { name: "各xyz周期ms", key: "rvs", default: "{500,500,500}" },
    LegacyDialog { name: "10透過率{始、終}", key: "lal", default: "{100,100}" },
    LegacyDialog { name: "周期ms", key: "als", default: "500" },
    LegacyDialog { name: "11拡大率{始、終}", key: "loz", default: "{100,100}" },
    LegacyDialog { name: "周期ms [2]", key: "zos", default: "500" },
    LegacyDialog { name: "12生存時間", key: "loj", default: "1" },
    LegacyDialog { name: "周期ms [3]", key: "jus", default: "500" },
    LegacyDialog { name: "13頻度", key: "lof", default: "100" },
    LegacyDialog { name: "周期ms [4]", key: "frs", default: "500" },
    LegacyDialog { name: "各ﾀｲﾌﾟ0~5", key: "loty", default: "{0,0,0,0,0,0,0,0,0,0,0,0,0}" },
];

pub(super) static SCHEMA_12: LegacyEffectSchema = LegacyEffectSchema {
    name: "時間", tracks: TRACKS_12, check: None, dialogs: DIALOGS_12, file_input: false,
};

static TRACKS_13: &[LegacyTrack] = &[
    LegacyTrack { name: "数", min: 0.0, max: 10.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "ﾊﾟﾗﾒｰﾀｰ", min: 1.0, max: 15.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "ｽｹｰﾙ", min: 0.1, max: 900.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "ｸﾞﾗﾌ切替", min: 1.0, max: 15.0, default: 1.0, step: 1.0 },
];
static DIALOGS_13: &[LegacyDialog] = &[
    LegacyDialog { name: "pos", key: "pos", default: "{-200,0,200,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0}" },
    LegacyDialog { name: "連結/chk", key: "cin", default: "0" },
];

pub(super) static SCHEMA_13: LegacyEffectSchema = LegacyEffectSchema {
    name: "時間2", tracks: TRACKS_13, check: Some(LegacyCheck { name: "グラフ表示", default: false }), dialogs: DIALOGS_13, file_input: false,
};

static TRACKS_14: &[LegacyTrack] = &[
    LegacyTrack { name: "xタイプ", min: 1.0, max: 4.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "yタイプ", min: 1.0, max: 4.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "zタイプ", min: 1.0, max: 4.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "球タイプ", min: 1.0, max: 3.0, default: 3.0, step: 1.0 },
];
static DIALOGS_14: &[LegacyDialog] = &[
    LegacyDialog { name: "x範囲", key: "xrange", default: "{-640,640}" },
    LegacyDialog { name: "y範囲", key: "yrange", default: "{-360,360}" },
    LegacyDialog { name: "z範囲", key: "zrange", default: "{-500,500}" },
    LegacyDialog { name: "xyz反発係数", key: "ex", default: "{0.9,0.9,0.9}" },
    LegacyDialog { name: "球位置", key: "pos", default: "{0,0,0}" },
    LegacyDialog { name: "球回転角", key: "thph", default: "{0,0}" },
    LegacyDialog { name: "球半径", key: "radi", default: "200" },
    LegacyDialog { name: "球反発係数", key: "er", default: "0.9" },
    LegacyDialog { name: "イレギュラー有/chk", key: "irreg", default: "0" },
    LegacyDialog { name: "確率", key: "prob", default: "30" },
    LegacyDialog { name: "領域内反射/chk", key: "inside", default: "1" },
    LegacyDialog { name: "ﾀｲﾌﾟ変更時間ms", key: "retime", default: "0" },
    LegacyDialog { name: "相対時間/chk", key: "reab", default: "0" },
    LegacyDialog { name: "各ﾀｲﾌﾟ変更", key: "retype", default: "{4,4,4,3}" },
    LegacyDialog { name: "出力5領域兼用/chk", key: "area56", default: "0" },
    LegacyDialog { name: "ﾌｨﾙﾀｰ1ﾘﾝｸ0~2", key: "reblink", default: "{0,0,0,0,0,0,0,0,0,0,0}" },
];

pub(super) static SCHEMA_14: LegacyEffectSchema = LegacyEffectSchema {
    name: "跳ね返り", tracks: TRACKS_14, check: Some(LegacyCheck { name: "領域表示", default: true }), dialogs: DIALOGS_14, file_input: false,
};

static TRACKS_15: &[LegacyTrack] = &[
];
static DIALOGS_15: &[LegacyDialog] = &[
    LegacyDialog { name: "ﾚｲﾔｰ", key: "relayer", default: "{}" },
    LegacyDialog { name: "各反発係数", key: "ree", default: "{0.9}" },
    LegacyDialog { name: "各ｲﾚｷﾞｭﾗｰ0~1", key: "reir", default: "{0}" },
    LegacyDialog { name: "各確率", key: "repro", default: "{30}" },
    LegacyDialog { name: "各領域反転0~1", key: "rere", default: "{0}" },
    LegacyDialog { name: "各ﾀｲﾌﾟ0~1", key: "retype", default: "{1}" },
    LegacyDialog { name: "各時間経過後0~1", key: "retime", default: "{1}" },
];

pub(super) static SCHEMA_15: LegacyEffectSchema = LegacyEffectSchema {
    name: "跳ね返り2", tracks: TRACKS_15, check: Some(LegacyCheck { name: "ｵﾌﾞｼﾞｪｸﾄ時間変化対応", default: false }), dialogs: DIALOGS_15, file_input: false,
};

static TRACKS_16: &[LegacyTrack] = &[
    LegacyTrack { name: "サイズ", min: 1.0, max: 500.0, default: 50.0, step: 1.0 },
    LegacyTrack { name: "装飾タイプ", min: 0.0, max: 4.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "ソート", min: 0.0, max: 2.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "切替間隔", min: 0.0, max: 100.0, default: 0.0, step: 1.0 },
];
static DIALOGS_16: &[LegacyDialog] = &[
    LegacyDialog { name: "テキスト", key: "pstr", default: "\"ここに文字\"" },
    LegacyDialog { name: "フォント", key: "font", default: "\"\"" },
    LegacyDialog { name: "色1/col", key: "scol1", default: "0xffffff" },
    LegacyDialog { name: "色2/col", key: "scol2", default: "0x000000" },
    LegacyDialog { name: "ﾊﾟｽ取得0~10", key: "gpath", default: "0" },
    LegacyDialog { name: "ﾌｧﾝﾈﾙ同期/chk", key: "fonfan", default: "0" },
];

pub(super) static SCHEMA_16: LegacyEffectSchema = LegacyEffectSchema {
    name: "テキスト", tracks: TRACKS_16, check: Some(LegacyCheck { name: "出力を一文字から行に", default: false }), dialogs: DIALOGS_16, file_input: false,
};

static TRACKS_17: &[LegacyTrack] = &[
    LegacyTrack { name: "ｻｲｽﾞ", min: 1.0, max: 500.0, default: 50.0, step: 1.0 },
    LegacyTrack { name: "形", min: 0.0, max: 8.0, default: 7.0, step: 1.0 },
    LegacyTrack { name: "ぱらばら", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "ﾊﾟｽ番号", min: 0.0, max: 10.0, default: 0.0, step: 1.0 },
];
static DIALOGS_17: &[LegacyDialog] = &[
    LegacyDialog { name: "画像ｻｲｽﾞ指定/chk", key: "pix", default: "0" },
    LegacyDialog { name: "画像ｻｲｽﾞpixel", key: "pixel", default: "{500,500}" },
    LegacyDialog { name: "出力背景色/chk", key: "opc", default: "0" },
    LegacyDialog { name: "背景指定ﾊﾟｽ番号", key: "pathn", default: "0" },
];

pub(super) static SCHEMA_17: LegacyEffectSchema = LegacyEffectSchema {
    name: "画像", tracks: TRACKS_17, check: Some(LegacyCheck { name: "中央のみ", default: false }), dialogs: DIALOGS_17, file_input: false,
};

static TRACKS_18: &[LegacyTrack] = &[
    LegacyTrack { name: "再生位置", min: 0.0, max: 100.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "再生速度", min: -5000.0, max: 5000.0, default: 100.0, step: 0.01 },
    LegacyTrack { name: "位置ﾗﾝﾀﾞﾑ", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "位置同期", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
];
static DIALOGS_18: &[LegacyDialog] = &[
    LegacyDialog { name: "再生速度ﾗﾝﾀﾞﾑ/chk", key: "srand", default: "0" },
    LegacyDialog { name: "再生速度ﾗﾝﾀﾞﾑ幅", key: "ranh", default: "{-800,800,0}" },
    LegacyDialog { name: "静止画連番出力/chk", key: "pic", default: "0" },
    LegacyDialog { name: "0無:1ｸﾛ:2ｶﾗｰｷｰ", key: "ttyp", default: "0" },
    LegacyDialog { name: "色相／輝度範囲", key: "ski", default: "0" },
    LegacyDialog { name: "彩度／色差範囲", key: "ssiki", default: "0" },
    LegacyDialog { name: "境界補正0~5", key: "ho", default: "0" },
    LegacyDialog { name: "色彩補正/chk", key: "sisa", default: "0" },
    LegacyDialog { name: "透過補正/chk", key: "toka", default: "0" },
    LegacyDialog { name: "色の取得/col", key: "keyc", default: "0x0000ff" },
];

pub(super) static SCHEMA_18: LegacyEffectSchema = LegacyEffectSchema {
    name: "動画", tracks: TRACKS_18, check: Some(LegacyCheck { name: "アルファ有", default: false }), dialogs: DIALOGS_18, file_input: false,
};

static TRACKS_19: &[LegacyTrack] = &[
    LegacyTrack { name: "数", min: 0.0, max: 10.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "風向xyz", min: 1.0, max: 3.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "ｽｹｰﾙ", min: 0.1, max: 100.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "ｸﾞﾗﾌ切替", min: 1.0, max: 3.0, default: 1.0, step: 1.0 },
];
static DIALOGS_19: &[LegacyDialog] = &[
    LegacyDialog { name: "pos", key: "pos", default: "{-200,0,200,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0,180,0}" },
    LegacyDialog { name: "発生場所", key: "happ", default: "nil" },
    LegacyDialog { name: "発生距離係数", key: "wdis", default: "100" },
    LegacyDialog { name: "空気抵抗", key: "are", default: "nil" },
    LegacyDialog { name: "連結/chk", key: "cin", default: "0" },
];

pub(super) static SCHEMA_19: LegacyEffectSchema = LegacyEffectSchema {
    name: "風", tracks: TRACKS_19, check: Some(LegacyCheck { name: "グラフ表示", default: false }), dialogs: DIALOGS_19, file_input: false,
};

static TRACKS_20: &[LegacyTrack] = &[
    LegacyTrack { name: "x方向", min: 0.0, max: 2000.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "y方向", min: 0.0, max: 2000.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "z方向", min: 0.0, max: 2000.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "間隔", min: 1.0, max: 1000.0, default: 10.0, step: 1.0 },
];
static DIALOGS_20: &[LegacyDialog] = &[
    LegacyDialog { name: "ﾊﾟﾀｰﾝ0~101", key: "apart", default: "0" },
    LegacyDialog { name: "\\ゆらぎ速度", key: "yuras", default: "180" },
    LegacyDialog { name: "\\ゆらぎ幅", key: "yurah", default: "{100,0,0,0}" },
    LegacyDialog { name: "\\個別{速度、幅}", key: "yurab", default: "{0,0}" },
    LegacyDialog { name: "@挙動不審/chk", key: "sus", default: "0" },
    LegacyDialog { name: "@不審確率", key: "susp", default: "30" },
    LegacyDialog { name: "@不審方向", key: "susvec", default: "{0,-100,0}" },
    LegacyDialog { name: "@不審速度", key: "sussp", default: "50" },
    LegacyDialog { name: "@不審間隔", key: "sustp", default: "30" },
    LegacyDialog { name: "#挙動不審Ⅱ/chk", key: "sus2", default: "0" },
    LegacyDialog { name: "#不審確率Ⅱ", key: "susp2", default: "30" },
    LegacyDialog { name: "#不審間隔Ⅱ", key: "sustp2", default: "30" },
    LegacyDialog { name: "*自作関数/chk", key: "orifunc", default: "0" },
    LegacyDialog { name: "*取得ﾊﾟｽ番号", key: "pathn", default: "0" },
    LegacyDialog { name: "*ｽｸﾘﾌﾟﾄ制御記述/chk", key: "scriptf", default: "0" },
];

pub(super) static SCHEMA_20: LegacyEffectSchema = LegacyEffectSchema {
    name: "挙動", tracks: TRACKS_20, check: Some(LegacyCheck { name: "ゆらぎ", default: false }), dialogs: DIALOGS_20, file_input: false,
};

static TRACKS_21: &[LegacyTrack] = &[
    LegacyTrack { name: "分散ﾀｲﾑms", min: 0.0, max: 90000.0, default: 1000.0, step: 1.0 },
    LegacyTrack { name: "xy拡散度", min: 0.0, max: 180.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "z拡散度", min: 0.0, max: 180.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "急停止ms", min: 0.0, max: 90000.0, default: 0.0, step: 1.0 },
];
static DIALOGS_21: &[LegacyDialog] = &[
    LegacyDialog { name: "分散角度均等/chk", key: "eqdeg", default: "0" },
    LegacyDialog { name: "回転同期/chk", key: "syncrot", default: "0" },
    LegacyDialog { name: "ﾌｨﾙﾀｰ同期0~1", key: "syncfil", default: "{0,0,0,0,0,0,0,0,0,0,0}" },
    LegacyDialog { name: "分散後軌跡表示/chk", key: "bigb", default: "0" },
    LegacyDialog { name: "反射で分散/chk", key: "resync", default: "0" },
    LegacyDialog { name: "分散平面", key: "plat", default: "\"{0,0}\"" },
    LegacyDialog { name: "分散後速度", key: "buvel", default: "\"\"" },
    LegacyDialog { name: "分散後加速度", key: "buac", default: "\"\"" },
    LegacyDialog { name: "ﾌｨﾙﾀｰ1分散0~2", key: "fillink", default: "{0,0,0,0,0,0,0,0,0,0,0}" },
    LegacyDialog { name: "個別{分時、止時}", key: "btime", default: "{0,0}" },
    LegacyDialog { name: "個別同期解除0~1", key: "clear", default: "{0,0}" },
    LegacyDialog { name: "分散停止ﾘﾝｸ0~2", key: "bslink", default: "0" },
    LegacyDialog { name: "↑ﾘﾝｸ時間ms", key: "bstime", default: "0" },
    LegacyDialog { name: "↑ﾘﾝｸ個別", key: "bsk", default: "0" },
];

pub(super) static SCHEMA_21: LegacyEffectSchema = LegacyEffectSchema {
    name: "挙動2", tracks: TRACKS_21, check: Some(LegacyCheck { name: "同時発生数同期", default: false }), dialogs: DIALOGS_21, file_input: false,
};

static TRACKS_22: &[LegacyTrack] = &[
    LegacyTrack { name: "中心x", min: -8000.0, max: 8000.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "中心y", min: -8000.0, max: 8000.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "中心z", min: -8000.0, max: 8000.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "角速度", min: -1000.0, max: 1000.0, default: 60.0, step: 1.0 },
];
static DIALOGS_22: &[LegacyDialog] = &[
    LegacyDialog { name: "ﾗﾝﾀﾞﾑ角速度/chk", key: "tmpb", default: "0" },
    LegacyDialog { name: "ﾗﾝﾀﾞﾑ値上下限", key: "dr", default: "{30,90,0}" },
    LegacyDialog { name: "角速度減加速", key: "tmpacc", default: "0" },
    LegacyDialog { name: "減速ﾏｲﾅｽ無/chk", key: "tmacn", default: "0" },
    LegacyDialog { name: "半径速度", key: "hd", default: "0" },
    LegacyDialog { name: "半径ﾏｲﾅｽ無/chk", key: "hn", default: "0" },
    LegacyDialog { name: "半径上限", key: "hlim", default: "nil" },
    LegacyDialog { name: "個別半径上限", key: "bhlim", default: "0" },
    LegacyDialog { name: "回転平面", key: "cirp", default: "\"{0,0}\"" },
    LegacyDialog { name: "中心ﾀｲﾌﾟ0~2", key: "eachc", default: "0" },
    LegacyDialog { name: "ﾀｲﾌﾟ2ﾗﾝﾀﾞﾑ範囲x", key: "rrx", default: "{-640,640}" },
    LegacyDialog { name: "ﾀｲﾌﾟ2ﾗﾝﾀﾞﾑ範囲y", key: "rry", default: "{-360,360}" },
    LegacyDialog { name: "ﾀｲﾌﾟ2ﾗﾝﾀﾞﾑ範囲z", key: "rrz", default: "{0,0}" },
    LegacyDialog { name: "球運動化/chk", key: "td", default: "0" },
];

pub(super) static SCHEMA_22: LegacyEffectSchema = LegacyEffectSchema {
    name: "挙動3", tracks: TRACKS_22, check: Some(LegacyCheck { name: "座標表示", default: true }), dialogs: DIALOGS_22, file_input: false,
};

static TRACKS_23: &[LegacyTrack] = &[
    LegacyTrack { name: "進行時間", min: -9999.0, max: 9999.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "微分表示", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "ﾗｽﾄ調整", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
];
static DIALOGS_23: &[LegacyDialog] = &[
    LegacyDialog { name: "放射時間", key: "ntime", default: "{{0,1},{2,nil}}" },
    LegacyDialog { name: "*活動時間", key: "atime", default: "{{0,1},{2,nil}}" },
    LegacyDialog { name: "*相対時間/chk", key: "la", default: "0" },
    LegacyDialog { name: "*連続性/chk", key: "conti", default: "0" },
    LegacyDialog { name: "*常に加速あり/chk", key: "nonvel", default: "0" },
];

pub(super) static SCHEMA_23: LegacyEffectSchema = LegacyEffectSchema {
    name: "挙動4", tracks: TRACKS_23, check: Some(LegacyCheck { name: "進行時間有効", default: false }), dialogs: DIALOGS_23, file_input: false,
};

static TRACKS_24: &[LegacyTrack] = &[
];
static DIALOGS_24: &[LegacyDialog] = &[
    LegacyDialog { name: "強さ", key: "strong", default: "50" },
    LegacyDialog { name: "影響開始時間ms", key: "inft", default: "0" },
    LegacyDialog { name: "↑ゆるやか変化/chk", key: "soft", default: "1" },
    LegacyDialog { name: "↑相対変化/chk", key: "rela", default: "1" },
    LegacyDialog { name: "領域間隔", key: "scaa", default: "100" },
    LegacyDialog { name: "強さ時間変化ms", key: "ftime", default: "0" },
    LegacyDialog { name: "個別空間場/chk", key: "indi", default: "0" },
    LegacyDialog { name: "空間乱数", key: "fran", default: "1" },
    LegacyDialog { name: "重たいけど/chk", key: "heavy", default: "0" },
];

pub(super) static SCHEMA_24: LegacyEffectSchema = LegacyEffectSchema {
    name: "空間場", tracks: TRACKS_24, check: Some(LegacyCheck { name: "z方向", default: false }), dialogs: DIALOGS_24, file_input: false,
};

static TRACKS_25: &[LegacyTrack] = &[
    LegacyTrack { name: "消失(ﾐﾘ秒", min: -5000.0, max: 5000.0, default: 300.0, step: 1.0 },
    LegacyTrack { name: "尻尾", min: 0.0, max: 8000.0, default: 100.0, step: 1.0 },
    LegacyTrack { name: "通過点数", min: 0.0, max: 1000.0, default: 2.0, step: 1.0 },
    LegacyTrack { name: "軌跡ﾀｲﾌﾟ", min: 0.0, max: 2.0, default: 0.0, step: 1.0 },
];
static DIALOGS_25: &[LegacyDialog] = &[
    LegacyDialog { name: "図形/fig", key: "figu", default: "\"\"" },
    LegacyDialog { name: "色/col", key: "col", default: "\"0xffffff\"" },
    LegacyDialog { name: "サイズ", key: "size", default: "10" },
    LegacyDialog { name: "尻尾透過率", key: "tral", default: "30" },
    LegacyDialog { name: "尻尾拡大率", key: "trzm", default: "30" },
    LegacyDialog { name: "間隔", key: "den", default: "5" },
    LegacyDialog { name: "ずれ幅", key: "jojo", default: "0" },
    LegacyDialog { name: "タイプ0重力あり/chk", key: "trgv", default: "0" },
    LegacyDialog { name: "軌跡用重力", key: "tgrav", default: "{nil,nil,nil}" },
    LegacyDialog { name: "通過点表示/chk", key: "passp", default: "0" },
    LegacyDialog { name: "通過透過率", key: "fral", default: "30" },
];

pub(super) static SCHEMA_25: LegacyEffectSchema = LegacyEffectSchema {
    name: "軌跡", tracks: TRACKS_25, check: Some(LegacyCheck { name: "カメラを見る", default: true }), dialogs: DIALOGS_25, file_input: false,
};

static TRACKS_26: &[LegacyTrack] = &[
    LegacyTrack { name: "数", min: 0.0, max: 500.0, default: 2.0, step: 1.0 },
    LegacyTrack { name: "ｻｲｽﾞ", min: 1.0, max: 500.0, default: 30.0, step: 1.0 },
    LegacyTrack { name: "半径", min: 1.0, max: 1500.0, default: 150.0, step: 1.0 },
    LegacyTrack { name: "円環数", min: 0.0, max: 100.0, default: 0.0, step: 1.0 },
];
static DIALOGS_26: &[LegacyDialog] = &[
    LegacyDialog { name: "図形/fig", key: "fig", default: "\"円\"" },
    LegacyDialog { name: "色/col", key: "col", default: "\"0xff0000\"" },
    LegacyDialog { name: "公転速度", key: "revo", default: "80" },
    LegacyDialog { name: "公転同期/chk", key: "fanlink", default: "0" },
    LegacyDialog { name: "自転速度", key: "rot", default: "50" },
    LegacyDialog { name: "円環{ｻｲｽﾞ、幅}", key: "csize", default: "{150,2}" },
    LegacyDialog { name: "円環図形/fig", key: "cfig", default: "\"円\"" },
    LegacyDialog { name: "円環自転速度", key: "crot", default: "50" },
    LegacyDialog { name: "円環自転同期/chk", key: "clink", default: "0" },
    LegacyDialog { name: "円環増分角度", key: "cdeg", default: "nil" },
    LegacyDialog { name: "透始終、拡始終", key: "falzo", default: "{100,50,100,100}" },
    LegacyDialog { name: "透過拡大同期0~1", key: "alzolink", default: "{0,0}" },
    LegacyDialog { name: "個別ｻｲ半径円ｻｲ", key: "ksrs", default: "{0,0,50}" },
    LegacyDialog { name: "3D0~1{公、自、円", key: "threed", default: "{0,0,0}" },
    LegacyDialog { name: "ﾌｨﾙﾀｰ適用0~2", key: "fanfil", default: "{1,1,1,1,1,1,1,1,1,1,1}" },
    LegacyDialog { name: "カメラ{ﾌｧﾝ、円}0~1", key: "fcam", default: "{0,0}" },
];

pub(super) static SCHEMA_26: LegacyEffectSchema = LegacyEffectSchema {
    name: "ファンネル", tracks: TRACKS_26, check: Some(LegacyCheck { name: "等間隔", default: false }), dialogs: DIALOGS_26, file_input: false,
};

static TRACKS_27: &[LegacyTrack] = &[
    LegacyTrack { name: "透過率", min: 0.0, max: 100.0, default: 100.0, step: 1.0 },
];
static DIALOGS_27: &[LegacyDialog] = &[
    LegacyDialog { name: "色/col", key: "mcol", default: "0xff0000" },
    LegacyDialog { name: "図形/fig", key: "mfig", default: "\"円\"" },
    LegacyDialog { name: "ﾗｲﾝ幅", key: "mwide", default: "10" },
    LegacyDialog { name: "間隔", key: "mdis", default: "1" },
    LegacyDialog { name: "同時発生で分ける/chk", key: "msync", default: "0" },
    LegacyDialog { name: "線から面/chk", key: "stom", default: "0" },
    LegacyDialog { name: "面積ﾌｪｰﾄﾞ", key: "mfade", default: "nil" },
    LegacyDialog { name: "面積時間透過率", key: "mtime", default: "nil" },
    LegacyDialog { name: "面積色複数", key: "mtcol", default: "{}" },
    LegacyDialog { name: "透過率乗算同期/chk", key: "malpha", default: "0" },
];

pub(super) static SCHEMA_27: LegacyEffectSchema = LegacyEffectSchema {
    name: "メッシュ", tracks: TRACKS_27, check: Some(LegacyCheck { name: "三次元", default: false }), dialogs: DIALOGS_27, file_input: false,
};

static TRACKS_28: &[LegacyTrack] = &[
    LegacyTrack { name: "タイプ", min: 0.0, max: 6.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "大きさ", min: 0.0, max: 500.0, default: 100.0, step: 1.0 },
    LegacyTrack { name: "分割数", min: 3.0, max: 20.0, default: 10.0, step: 1.0 },
    LegacyTrack { name: "パス番号", min: 1.0, max: 10.0, default: 1.0, step: 1.0 },
];
static DIALOGS_28: &[LegacyDialog] = &[
    LegacyDialog { name: "ﾀｲﾌﾟ4横曲率", key: "kyoku1", default: "50" },
    LegacyDialog { name: "ﾀｲﾌﾟ4横半径", key: "rw", default: "50" },
    LegacyDialog { name: "ﾀｲﾌﾟ4縦曲率", key: "kyoku2", default: "20" },
    LegacyDialog { name: "ﾀｲﾌﾟ4縦半径", key: "rh", default: "100" },
    LegacyDialog { name: "ﾀｲﾌﾟ4速度", key: "bata", default: "0" },
    LegacyDialog { name: "ﾀｲﾌﾟ5奥行き", key: "oku", default: "100" },
    LegacyDialog { name: "ﾀｲﾌﾟ6中心位置", key: "center", default: "0" },
];

pub(super) static SCHEMA_28: LegacyEffectSchema = LegacyEffectSchema {
    name: "立体物", tracks: TRACKS_28, check: Some(LegacyCheck { name: "アンチエイリアス", default: true }), dialogs: DIALOGS_28, file_input: false,
};

static TRACKS_29: &[LegacyTrack] = &[
    LegacyTrack { name: "倍率", min: 0.0, max: 200.0, default: 100.0, step: 1.0 },
    LegacyTrack { name: "水平位置", min: 0.0, max: 100.0, default: 50.0, step: 1.0 },
    LegacyTrack { name: "垂直位置", min: 0.0, max: 100.0, default: 50.0, step: 1.0 },
    LegacyTrack { name: "ｴｯｼﾞ角", min: -360.0, max: 360.0, default: 45.0, step: 1.0 },
];
static DIALOGS_29: &[LegacyDialog] = &[
    LegacyDialog { name: "ｴｯｼﾞ高さ", key: "ehigh", default: "1" },
    LegacyDialog { name: "ｴｯｼﾞ幅", key: "ewild", default: "5" },
    LegacyDialog { name: "ぼかし", key: "bo", default: "0" },
    LegacyDialog { name: "光の強さ", key: "light", default: "10" },
    LegacyDialog { name: "縦横比", key: "tyh", default: "0" },
    LegacyDialog { name: "ﾌｨﾙﾀｰ順序調整/chk", key: "fiturn", default: "0" },
    LegacyDialog { name: "精度", key: "ss", default: "20" },
];

pub(super) static SCHEMA_29: LegacyEffectSchema = LegacyEffectSchema {
    name: "ガラス化(二次元)", tracks: TRACKS_29, check: Some(LegacyCheck { name: "反転", default: false }), dialogs: DIALOGS_29, file_input: false,
};

static TRACKS_30: &[LegacyTrack] = &[
    LegacyTrack { name: "番号", min: 0.0, max: 999.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "値1", min: -9999.0, max: 9999.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "値2", min: -9999.0, max: 9999.0, default: 0.0, step: 0.01 },
    LegacyTrack { name: "値3", min: -9999.0, max: 9999.0, default: 0.0, step: 1.0 },
];
static DIALOGS_30: &[LegacyDialog] = &[
    LegacyDialog { name: "設定値1", key: "p_v_1", default: "0" },
    LegacyDialog { name: "設定値2", key: "p_v_2", default: "0" },
    LegacyDialog { name: "設定値3", key: "p_v_3", default: "0" },
    LegacyDialog { name: "設定値4", key: "p_v_4", default: "0" },
    LegacyDialog { name: "設定値5", key: "p_v_5", default: "0" },
    LegacyDialog { name: "設定値6", key: "p_v_6", default: "0" },
    LegacyDialog { name: "設定値7", key: "p_v_7", default: "0" },
    LegacyDialog { name: "設定値8", key: "p_v_8", default: "0" },
    LegacyDialog { name: "色1/col", key: "p_c_1", default: "0xffffff" },
    LegacyDialog { name: "色2/col", key: "p_c_2", default: "0xffffff" },
    LegacyDialog { name: "図形1/fig", key: "p_f_1", default: "\"円\"" },
    LegacyDialog { name: "図形2/fig", key: "p_f_2", default: "\"円\"" },
    LegacyDialog { name: "ﾁｪｯｸﾎﾞｯｸｽ1/chk", key: "p_b_1", default: "0" },
    LegacyDialog { name: "ﾁｪｯｸﾎﾞｯｸｽ2/chk", key: "p_b_2", default: "0" },
    LegacyDialog { name: "使用引数", key: "oncode", default: "{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}" },
    LegacyDialog { name: "使い方表示/chk", key: "disp", default: "0" },
];

pub(super) static SCHEMA_30: LegacyEffectSchema = LegacyEffectSchema {
    name: "ﾕｰｻﾞｰｶｽﾀﾑｵﾌﾞｼﾞｪｸﾄ", tracks: TRACKS_30, check: Some(LegacyCheck { name: "相対時間", default: true }), dialogs: DIALOGS_30, file_input: false,
};

static TRACKS_31: &[LegacyTrack] = &[
];
static DIALOGS_31: &[LegacyDialog] = &[
    LegacyDialog { name: "ランダム値設定", key: "r1", default: "{0,0,0,0}" },
    LegacyDialog { name: "ランダム値設定 [2]", key: "r2", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [3]", key: "r3", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [4]", key: "r4", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [5]", key: "r5", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [6]", key: "r6", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [7]", key: "r7", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [8]", key: "r8", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [9]", key: "r9", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [10]", key: "r10", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [11]", key: "r11", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [12]", key: "r12", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [13]", key: "r13", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [14]", key: "r14", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [15]", key: "r15", default: "nil" },
    LegacyDialog { name: "ランダム値設定 [16]", key: "r16", default: "nil" },
];

pub(super) static SCHEMA_31: LegacyEffectSchema = LegacyEffectSchema {
    name: "他作ｱﾆﾒｰｼｮﾝ効果ｵﾌﾟｼｮﾝ", tracks: TRACKS_31, check: Some(LegacyCheck { name: "微調整", default: false }), dialogs: DIALOGS_31, file_input: false,
};

static TRACKS_32: &[LegacyTrack] = &[
    LegacyTrack { name: "取得位置", min: 1.0, max: 10.0, default: 1.0, step: 1.0 },
    LegacyTrack { name: "取得2", min: 0.0, max: 10.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "頻度", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
    LegacyTrack { name: "速度", min: 0.0, max: 1.0, default: 0.0, step: 1.0 },
];
static DIALOGS_32: &[LegacyDialog] = &[
    LegacyDialog { name: "ﾌｧｲﾙ名", key: "fn", default: "\"particle001\"" },
    LegacyDialog { name: "録音/chk", key: "rawd", default: "0" },
    LegacyDialog { name: "開始時間ずれ", key: "subtime", default: "0" },
    LegacyDialog { name: "頻度倍率", key: "fmag", default: "100" },
    LegacyDialog { name: "↑算出方法加算/chk", key: "fcal", default: "1" },
    LegacyDialog { name: "速度倍率", key: "vmag", default: "100" },
    LegacyDialog { name: "↑算出方法加算/chk [2]", key: "vcal", default: "0" },
    LegacyDialog { name: "もう一か所取得", key: "another", default: "0" },
    LegacyDialog { name: "挙動3のみに対応/chk", key: "roton", default: "0" },
];

pub(super) static SCHEMA_32: LegacyEffectSchema = LegacyEffectSchema {
    name: "音", tracks: TRACKS_32, check: Some(LegacyCheck { name: "いまの音を取得", default: true }), dialogs: DIALOGS_32, file_input: false,
};

pub(super) static SCHEMAS: &[&LegacyEffectSchema] = &[
    &SCHEMA_1,
    &SCHEMA_2,
    &SCHEMA_3,
    &SCHEMA_4,
    &SCHEMA_5,
    &SCHEMA_6,
    &SCHEMA_7,
    &SCHEMA_8,
    &SCHEMA_9,
    &SCHEMA_10,
    &SCHEMA_11,
    &SCHEMA_12,
    &SCHEMA_13,
    &SCHEMA_14,
    &SCHEMA_15,
    &SCHEMA_16,
    &SCHEMA_17,
    &SCHEMA_18,
    &SCHEMA_19,
    &SCHEMA_20,
    &SCHEMA_21,
    &SCHEMA_22,
    &SCHEMA_23,
    &SCHEMA_24,
    &SCHEMA_25,
    &SCHEMA_26,
    &SCHEMA_27,
    &SCHEMA_28,
    &SCHEMA_29,
    &SCHEMA_30,
    &SCHEMA_31,
    &SCHEMA_32,
];

