param(
    [string]$InputPath = "particle_r_evidence/parameters.json",
    [string]$OutputPath = "crates/particle-aviutl2/src/legacy_ui_data.rs"
)

$ErrorActionPreference = "Stop"

function RustString([string]$Value) {
    if ($null -eq $Value) { $Value = "" }
    '"' + $Value.Replace('\', '\\').Replace('"', '\"').Replace("`r", '').Replace("`n", '\n') + '"'
}

function NumberOr([string]$Value, [string]$Fallback) {
    if ([string]::IsNullOrWhiteSpace($Value)) { return $Fallback }
    $parsed = 0.0
    if ([double]::TryParse($Value, [Globalization.NumberStyles]::Float, [Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
        $result = $parsed.ToString('R', [Globalization.CultureInfo]::InvariantCulture)
        if ($result -notmatch '[\.Ee]') { $result += '.0' }
        return $result
    }
    return $Fallback
}

$effects = Get-Content -LiteralPath $InputPath -Raw -Encoding utf8 | ConvertFrom-Json
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// @generated by scripts/generate_legacy_ui.ps1; do not edit by hand.')

foreach ($effect in $effects) {
    $id = [int]$effect.index
    $lines.Add("static TRACKS_$id`: &[LegacyTrack] = &[")
    foreach ($track in $effect.tracks) {
        $label = RustString ([string]$track.label)
        $min = NumberOr ([string]$track.min_raw) '0.0'
        $max = NumberOr ([string]$track.max_raw) '0.0'
        $default = NumberOr ([string]$track.default_raw) '0.0'
        $step = NumberOr ([string]$track.step_raw) '1.0'
        $lines.Add("    LegacyTrack { name: $label, min: $min, max: $max, default: $default, step: $step },")
    }
    $lines.Add('];')

    $check = 'None'
    if ($effect.checks_raw.Count -gt 0 -and ([string]$effect.checks_raw[0]) -match '^--check\d+:(.*),([01]);?$') {
        $checkName = RustString $Matches[1]
        $checkDefault = if ($Matches[2] -eq '1') { 'true' } else { 'false' }
        $check = "Some(LegacyCheck { name: $checkName, default: $checkDefault })"
    }

    $dialogs = [Collections.Generic.List[object]]::new()
    foreach ($dialogRaw in $effect.dialogs_raw) {
        foreach ($part in ([string]$dialogRaw -split ';')) {
            $part = $part.Trim()
            if (-not $part) { continue }
            if ($part -match '^(.*?),(?:local\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$') {
                $dialogs.Add([pscustomobject]@{
                    Label = $Matches[1]
                    Key = $Matches[2]
                    Default = $Matches[3]
                })
            }
        }
    }
    $lines.Add("static DIALOGS_$id`: &[LegacyDialog] = &[")
    $seen = @{}
    foreach ($dialog in $dialogs) {
        $label = [string]$dialog.Label
        if ($seen.ContainsKey($label)) {
            $seen[$label]++
            $display = "$label [$($seen[$label])]"
        } else {
            $seen[$label] = 1
            $display = $label
        }
        $displayString = RustString $display
        $keyString = RustString ([string]$dialog.Key)
        $defaultString = RustString ([string]$dialog.Default)
        $lines.Add("    LegacyDialog { name: $displayString, key: $keyString, default: $defaultString },")
    }
    $lines.Add('];')
    $lines.Add("")
    $name = RustString ([string]$effect.name)
    $fileInput = if ($effect.file_input) { 'true' } else { 'false' }
    $lines.Add("pub(super) static SCHEMA_$id`: LegacyEffectSchema = LegacyEffectSchema {")
    $lines.Add("    name: $name, tracks: TRACKS_$id, check: $check, dialogs: DIALOGS_$id, file_input: $fileInput,")
    $lines.Add('};')
    $lines.Add('')
}

$lines.Add('pub(super) static SCHEMAS: &[&LegacyEffectSchema] = &[')
foreach ($effect in $effects) {
    $id = [int]$effect.index
    $lines.Add("    &SCHEMA_$id,")
}
$lines.Add('];')
$lines.Add('')

$parent = Split-Path -Parent $OutputPath
if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
[IO.File]::WriteAllLines((Join-Path (Get-Location) $OutputPath), $lines, [Text.UTF8Encoding]::new($false))
Write-Output "Generated $OutputPath from $InputPath ($($effects.Count) effects)"
